version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: project_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: project_planner      
    ports:
      - "3306:3306"
    volumes:
    - project_mysql_data:/var/lib/mysql

volumes:
  project_mysql_data:
