version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: project_planner_mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with your desired root password
      MYSQL_DATABASE: project_planner      # The name of the database to create
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql          # Mount a volume to persist MySQL data

volumes:
  mysql_data:
